add: Add the WangAn record number at the footer content. resolve #191
yrccondor/mdx pull request #192
Opened 2021-08-18 12:27 UTC by AH-dark

增加了网安备案号

在此代码中，Axton著作权声明、网安备案号、ICP备案号将会等距排列，如图
[![1629289042809.png](https://i1-qiniu.s.ahdark.com/202108/18/cefa1d34814a9.png/index.webp)](https://i1-qiniu.s.ahdark.com/202108/18/cefa1d34814a9.png/index.webp)
> 小图标为公安部要求的必须添加的图标，我以Base64编码的形式嵌入了进去
> （虽然更好的方法是图片URL，但我怕被怀疑打广告）

此代码还需要一些额外的修正，这可能需要 @yrccondor 完成

- CSS样式 `mdx-footer-content` 可以移除，此样式仅包括了 `float: right` ，而在修正后底部将采用Flex样式 [![1629289193003.png](https://i1-qiniu.s.ahdark.com/202108/18/d508e936fa711.png/index.webp)](https://i1-qiniu.s.ahdark.com/202108/18/d508e936fa711.png/index.webp)
- 我并未实验 _现代_ 以外的页脚样式（因为没有合适的环境），因此可能还需进一步调整和测试。当然 _现代_ 的页脚样式是可以完美适配的

衷心希望允许合入，我很期待并很荣幸成为MDx的Committer之一

PS：我把这个**代码格式化了一下，因为这个实在没法看，请不要生气

2021-08-18 12:29 UTC, AH-dark commented
For this Pull Request, you can check #191 Issue.

2021-08-18 15:47 UTC, yrccondor commented
非常欢迎进行贡献！

功能确认 OK，但希望可以对 base64 进行压缩或是将图片放入 MDx 的图片文件夹并引用。这个体积的图片已经不适合内嵌了，会降低加载性能。

此外对于代码的格式化：
1. 我欢迎对代码进行格式化
2. PHP 中部分内容依赖于正确的空格（如拼接生成 HTML 标签），**这需要进一步的检查**
3. 在 PHP 中引入额外的空格会导致最终 HTML 体积增加，但目前 MDx 并没有合适的方案在主题发布给用户前对此进行优化，仍需考虑
4. CSS 文件的格式化不符合 MDx 的常用风格，我可能会考虑将其 revert

2021-08-18 15:48 UTC, yrccondor requested changes

2021-08-18 15:48 UTC, yrccondor commented on footer.php
> +                                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKTWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVN3WJP3Fj7f92UPVkLY8LGX
建议压缩或提取为文件

2021-08-19 02:03 UTC, AH-dark commented on footer.php
> +                                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKTWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVN3WJP3Fj7f92UPVkLY8LGX
改了，图标文件在```/imgg/beian.png```（来自beian.gov.cn），用了```$files_root```，具体参见Commit ac1a336

2021-08-19 02:08 UTC, AH-dark commented
那个 原有依赖项不完善（6efbf1a） 当放屁了就行，提错了，依赖项不完善的是wordpress

2021-08-19 11:50 UTC, AH-dark commented
好了我自己revert了

2021-08-19 19:02 UTC, yrccondor commented
非常感谢！我需要花一些时间检查，尽量在今日稍晚合并

BTW 如果你有空可以把 tab 缩进 revert 回空格缩进...

2021-08-20 06:29 UTC, AH-dark commented
改空格缩进了

Axton giegie 我爱你

2021-08-22 15:16 UTC, yrccondor approved these changes

2021-08-22 15:33 UTC, merged